[package]
name = "ancvm_assembly_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ancvm_types = { path = "../../../xiaoxuan-core-vm/crates/types" }

[dev-dependencies]
pretty_assertions = "1.4.0"
